[KIECLOUD-453] - Use unique names for product artifacts
jboss-container-images/rhdm-7-image pull request #402
Opened 2020-11-16 16:21 UTC by spolti

Signed-off-by: spolti <fspolti@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [x] Pull Request title is properly formatted: `[RHDM-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted
- [x] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [x] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2020-11-16 16:47 UTC, msmagnanijr submitted a review, later dismissed

2020-11-17 05:06 UTC, Kaitou786 approved these changes

2020-11-18 09:52 UTC, jakubschwan approved these changes

2020-11-18 20:16 UTC, msmagnanijr submitted a review, later dismissed

2020-11-19 08:07 UTC, jakubschwan requested changes

2020-11-19 08:07 UTC, jakubschwan commented on README.md
> +  value: "rhdm-decision_central_distribution.zip"
```suggestion
  value: "rhdm_decision_central_distribution.zip"
```

2020-11-19 08:07 UTC, jakubschwan commented on README.md
> +- name: "rhdm-decision_central_distribution.zip"
```suggestion
- name: "rhdm_decision_central_distribution.zip"
```

2020-11-19 10:19 UTC, Kaitou786 submitted a review, later dismissed
Looks good after Jakub suggestions

2020-11-19 19:07 UTC, Kaitou786 approved these changes

2020-11-19 20:22 UTC, msmagnanijr approved these changes

2020-11-20 08:32 UTC, jakubschwan approved these changes

2020-11-20 15:23 UTC, merged